### ISSUE TITLE
DateTypeConverter does not handle serialized default DateTime values

### ISSUE THREAD

**Issue by bnordli** [dolittle/Bifrost#644]
Using NewtonSoft.Json, the default serialization format of DateTimes is the ISO 8601 standard. And the ISO 8601 format of .NETs default(DateTime) is "0001-01-01T00:00:00".

The new DateTypeConverter doesn't handle round trips of this value (at least in Chrome and Firefox).
Chrome:

    var converter = Bifrost.values.DateTypeConverter.create()
    var d = converter.convertFrom("0001-01-01T00:00:00")
    // result: Mon Jan 01 1 (and a time zone specific time)
    var e = converter.convertFrom(d.toString())
    // result: Mon Jan 01 **2001** (and the same time zone specific time)

Even weirder in Firefox

    var converter = Bifrost.values.DateTypeConverter.create()
    var d = converter.convertFrom("0001-01-01T00:00:00")
    // result: Date 0000-12-31T23:00:00 (or something similar)
    var e = converter.convertFrom(d.toString())
    // or even var e = converter.convertFrom(d)
    // result: Invalid Date

This happens regularily when a read model is loaded into a command. First, the response text is converted into the read model. (Setting a value equal to d on the read model.)
Next, the read model values is copied into the command, **calling toString() on d** in Bifrost.mapping.copyProperties(), resulting in a value equal to e in the command.

Suggested fix: Treating default(DateTime) values from .NET as null in js. Amending DateTypeConverter like this:

    this.convertFrom = function (value) {
      if (value == "0001-01-01T00:00:00") {
        return null;
      }
      var date = new Date8value);
      return date;
    }

Alternatively, remove
value = typeConverters.convertFrom(value~~.toString()~~, typeAsString())
in Bifrost.mapping ..but the toString is probably there for a reason..

**Comment by bnordli** [comment]
..and in Internet Explorer, any attempts to access new Date("0001-01-01T00:00:00") result in disaster

I think the only reasonable interpretation of this string is 'null' in JavaScript.

**Comment by einari** [comment]
Is the the pull request I merged from you??  Can we close it, or does it need more investigation?

**Comment by bnordli** [comment]
This was fixed in the branch aptly named issue-644, yes ;-)
9. mai 2015 16.44 skrev "Einar Ingebrigtsen" <notifications@github.com>:
>
> Is the the pull request I merged from you?? Can we close it, or does it
need more investigation?

**Comment by einari** [comment]
LOL.. Sorry about that. Didn't look at the name - then its pulled and I'll close this..
