### ISSUE TITLE
TypeDiscoverer is extremely slow (again)

### ISSUE THREAD

**Issue by bnordli** [dolittle/Bifrost#657]
Caching of implemented types was added in #426, but was recently removed (commit 3e787da81d72146af496bc68191ba7b971a3ce8b).

It is imperative that caching of implemented interfaces is kept! Profiling ProCoSys with Bifrost 1.0.0.28 takes 30-50 seconds (!) for each request to Bifrost/Security, with most of the time spent inside RuntimeType.GetInterface.

**Comment by einari** [comment]
Looked at the cache when refactoring this and just concluded - that can't be that slow as to need a caching mechanism. And out it went.. :8ball:    What I say about the word assume applies here..  It just makes an *Ass* out of *U* & *Me*.

I'll have a look at it ASAP.

**Comment by bnordli** [comment]
Small update: Most of the seconds spent in Bifrost/Security for us was because of a cache that didn't work properly. But still: Profiling of a small sample useage of the ProCoSys app shows 40% time spent in TypeFinder.FindMultiple, so this is still an important issue.
