### ISSUE TITLE
NullReferenceException in DefaultCallContext fails in multi-threaded environments

### ISSUE THREAD

**Issue by bnordli** [dolittle/Bifrost#665]
Even though DefaultCallContext pretends to be thread safe by using a ThreadStatic attribute on its data dictionary, only the first thread ever sees a non-null dictionary. (See first note in https://msdn.microsoft.com/en-us/library/system.threadstaticattribute.aspx.)

Solution: _data should be wrapped by a (private) property that checks for null on each access.

**Comment by bnordli** [comment]
Sorry. This isn't in Bifrost code.

**Comment by bnordli** [comment]
Yes, it is, actually. (But we are using a copy with the same error, and can modify our for the moment.)

**Comment by einari** [comment]
:)   Ok..   Will have a look at it - got a few things on my plate for a couple of days, hope you can live without a fix for that long.

**Comment by einari** [comment]
This is the same as #706 - confirmed. The pull request fixes the problem. Thanks.
Merged and set to go.. :)
