### ISSUE TITLE
Bifrost Assetsmanager could use an exclusion list

### ISSUE THREAD

**Issue by andersnygaard** [dolittle/Bifrost#668]
It seems Bifrost is loading all assets in all folders starting at the System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath. Now, in our case, we have resources in our bin folder that are used server side only, but are now exposed to the client. What we need is an exclude list that can be configured in our application and be respected by the Bifrost.Web.Assets.IAssetsManager.

A workaround solution for now is to implement our own IAssetsManager with a custom Initialize() method.
![xul](https://cloud.githubusercontent.com/assets/1021464/9933602/3dd55188-5d4c-11e5-90d7-8f727c131c2a.png)

**Comment by einari** [comment]
The asset manager only exposes what is available on the server - not the actual content of the assets. But I agree, there needs a mechanism to exclude these.

**Comment by bnordli** [comment]
This is fixed in the ProCoSys fork.

**Comment by bnordli** [comment]
This was actually fixed by #669 and can be closed.
