### ISSUE TITLE
Generate bifrost.debug.js by MsBuild instead of hlin

### ISSUE THREAD

**Issue by bnordli** [dolittle/Bifrost#707]
(Copied from https://github.com/ProCoSys/Bifrost/issues/35)

hlin is a custom tool to bundle together many js files into bifrost.debug.js.

It is currently run on each build of Bifrost.JavaScript and has the unfortunate side effect of updating the file time stamp even though the contents has not changed. This confuses git.

In essence, hlin is really simple and can be replaced by a custom MsBuild task. MsBuild can properly do dependency analysis and only regbuild bifrost.debug.js when necessary.

**Comment by einari** [comment]
Good point.

I'm looking at bringing the whole JavaScript part into a more modern way - most likely built on top of SystemJS and JSPM. I'm also investigating which is better of WebPack and JSPM. But then these tools would do this. That means that the file will pretty much go away and be part of deployment during the Continuous Deployment build

**Comment by bnordli** [comment]
I understand where you want to go, but this is actually quite an annoyance!

I am using Git for Windows, and bifrost.debug.js is continuously in the "Unstaged changes" category. When this is the only file there, it is automatically selected and the following dialog appears:

![image](https://cloud.githubusercontent.com/assets/5574761/21657758/0befbf7a-d2c4-11e6-82d8-254b019d8ab3.png)

In addition, changing branches and rebasing often gives the following error:
```
error: Your local changes to the following files would be overwritten by chect:
        Source/Bifrost.JavaScript/Bifrost.debug.js
Please commit your changes or stash them before you switch branches.
Aborting
```
I am happy to accept any other solution that keeps the file stamp of the file intact, but this is a very simple fix that additionally removes a dependency on a non-standard tool.

**Comment by bnordli** [comment]
Thanks for taking this! :)
