### ISSUE TITLE
Automatically use origin of the Bifrost Application script as the origin for requests

### ISSUE THREAD

**Issue by einari** [dolittle/Bifrost#827]
Views + ViewModels + performing things through Server.js - POST / GET - base-URL - by convention use the origin of the Bifrost Application script:

```javascript
var currentScript = document.currentScript || (function() {
  var scripts = document.getElementsByTagName('script');
  return scripts[scripts.length - 1];
})();
```
Found [here](http://2ality.com/2014/05/current-script.html)

**Comment by svethors** [comment]
Latest pull request for this issue has a tentative fix for commands, and a slightly different implementation that does not require Bifrost to be the last script tag in the html document. It uses jQuery to select the script tag that has an src containing "Bifrost/Application".

The above convention for views and viewmodels seem to have the same requirement?

This caused problems when adding a require config section, with text -> useXhr returning true, after the Bifrost/Application script tag. This config should however probably be part of Bifrost?
