### ISSUE TITLE
Different version on stateful and stateless aggregat roots

### ISSUE THREAD

**Issue by rogertorhov** [dolittle/Bifrost#837]
### Description
When the aggregat root has no state the version is 1.0, but should be 0.0

**Comment by einari** [comment]
If one does not configure a EventSourceVersions - such as Redis - the NullEventSourceVersions always returned `EventSourceVersions.Zero`. The fix implemented will work for NullEventSourceVersions and actually forwards the request to the EventSource, which has support for getting the version based on the events. The Redis option is an optimization option.
